# Generated by Django 4.2.2 on 2023-06-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='proflie_image',
            new_name='profile_image',
        ),
    ]
