# Generated by Django 4.2.2 on 2023-06-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailcheckcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcheckcode',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
