# Generated by Django 4.2.2 on 2023-06-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_emailcheckcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcheckcode',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
