# Generated by Django 4.1.2 on 2023-06-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_options_post_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_info',
        ),
    ]
